on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-templates:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes
    
    steps:      
      - name: Meow Maker for Catppuccin
        uses: grokdesigns/meow-maker@v1.0.1  # Use your new version
        with:
          git_username: "github-actions[bot]"
          git_email: "github-actions[bot]@users.noreply.github.com"
          skip_ci: "yes"
          input_folder: "templates"
          output_folder: "output"
          commit_message: "ğŸ± - Generated via Meow Maker"
