name: Meow Maker Workflow
on:
  push:
    branches:
      - master
jobs:
  Meow-Maker-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Meow Maker for Catppuccin
        uses: grokdesigns/meow-maker@v1.0.5
        with:
          git_username: 'github-actions[bot]'
          git_email: 'github-actions[bot]@users.noreply.github.com'
          skip_ci: 'yes'
          commit_message: 'ğŸ± - Generated via Meow Maker'
          output_folder: 'outputtest'
          input_folder: 'templates'
          branch_name: ${{ github.ref }}  #Don't change.
